export const reasonCodesV1_1 = {
  DATA_MISSING: "DATA_MISSING",
  DATA_FRESH: "DATA_FRESH",
  FOLLOW_PLAN: "FOLLOW_PLAN",
  NO_PLAN_TODAY: "NO_PLAN_TODAY",
  LOAD_GUARD: "LOAD_GUARD",
  FATIGUE_HIGH: "FATIGUE_HIGH",
  READINESS_LOW: "READINESS_LOW",
  OPTIMIZE_VOLUME_DOWN: "OPTIMIZE_VOLUME_DOWN",
  OPTIMIZE_INTENSITY_DOWN: "OPTIMIZE_INTENSITY_DOWN",
} as const;

export type ReasonCodeV1_1 = (typeof reasonCodesV1_1)[keyof typeof reasonCodesV1_1];

